version: "2"

services:
  nodered:
    image: nodered/node-red
    container_name: "nodered"
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "1880:1880"
  
  influxdb:
    image: influxdb:latest
    #ports:
    #   - '8086:8086'
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    env_file: .env
    environment:
      - INFLUXDB_DB=${INFLUXDB_NAME}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
   
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-storage:/mosquitto/data
      # - ./mosquitto.log:/mosquitto/log/mosquitto.log
    environment:
      - PUID=1883
      - PGID=1883
    restart: always
    network_mode: host
    # expose:
    #  - "1883"
    #  - "9001"
    ports:
      - 1883:1883
      #   - '9001'

volumes:
  mosquitto-storage:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
